### ISSUE TITLE
Bug occam2d_rewrite

### ISSUE THREAD

**Issue by ralfschaa** [geophysics/mtpy#31]
Hi all,

I encountered the following in the occam2d_rewrite module, near line 1058:

`self.geoelectric_strike = np.median(np.nonzero(strike_angles))`

this is a bug: np.nonzero return an array of integers (indices where strike_angles is non-zero).

Question: is this the correct module to use for creating an Occam2D datafile?

Cheers
-Ralf

**Comment by kujaku11** [comment]
Good catch, I just found that one a second ago.  I'll change that accordingly.

Yes, use the occam2d_rewrite to create a data file, its the most up to date version, the others are legacy files that will be deprecated in the next update.

Cheers
