### ISSUE TITLE
Rotation in legacy code

### ISSUE THREAD

**Issue by ralfschaa** [geophysics/mtpy#32]
Hi all,

I encountered the following code in function _get_station_data (Class Occam2DData in legacy):

```
self.thetar = thetar
if abs(self.thetar) > 2*np.pi:
    self.thetar = self.thetar*(np.pi/180)
```

this converts degree-angles larger than 2PI (why is that?) to radian-angles

However all subsequent code seem to expect degree-angles.

Here is code just before the rotation is done (in function rotatematrix_incl_errors in utils/calculator.py):

`phi = math.radians(degreeangle)`

which again converts to radian.

I don't think this is correct.

Cheers
-Ralf

**Comment by kujaku11** [comment]
Thanks Ralf,

This is why this code is going to be deprecated in future versions.

Cheers

**Comment by ralfschaa** [comment]
Thanks JP, good to know.
