### ISSUE TITLE
Small bug in modem

### ISSUE THREAD

**Issue by ralfschaa** [geophysics/mtpy#33]
Hi all,

near line 699 in modem_new.py:

`self.data_array[ii]['z_err'][jj] = interp_z.z_err[kk, :, :]`

but `interp_z` has attribute `zerr `not `z_err`

(same with `interp_t.tippererr`)

Cheers
-Ralf

**Comment by alkirkby** [comment]
Thanks Ralf,

I’ve updated modem_new to fix that bug and your more recent one.

Cheers, Alison.

**Comment by ralfschaa** [comment]
Great, and thanks for MTPy!
