### ISSUE TITLE
there is a bug in ws3dinv.py

### ISSUE THREAD

**Issue by chenhaomagnetic** [geophysics/mtpy#44]
>>> import mtpy.modeling.ws3dinv as ws   
 >>>import os
.............................
 >>> mm = ws.WS3DModelManipulator(initial_fn=wsmesh.initial_fn)

  here is no WS3DModelManipulator function in the module of ws3dinv.py  and it will get a error. but there is a function WSModelManipulator,I have tried it,  it also get a error.

**Comment by alkirkby** [comment]
Hi- This repository has been moved to MTGeophysics/mtpy - please install MTPy from there and see if you still get an error.

**Comment by chenhaomagnetic** [comment]
yse, I am sure the package I installed is come from  MTGeophysics/mtpy.
Could you modify it.

Alison Kirkby <notifications@github.com> 于2018年11月12日周一 上午7:23写道：

**Comment by alkirkby** [comment]
Please re-log the bug in the issues page on MTGeophysics/mtpy.
Please provide some more details about the bug following the template provided.
I may or may not be able to help with this one as I didn't write this package and do not use WSInv3d. But one of the other developers might.
